apiVersion: v1
kind: Service
metadata:
  name: {{ include "camel-web-service.fullname" . }}
  labels:
    {{- include "camel-web-service.labels" . | nindent 4 }}
  annotations:
    {{ .Values.service.port }}.service.kuma.io/protocol: http
    8080.service.kuma.io/protocol: http
    ingress.kubernetes.io/service-upstream: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
    - name: actuator
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: kuma-virtual-probe
      port: 19001
      protocol: TCP
      targetPort: 19001
  selector:
    {{- include "camel-web-service.selectorLabels" . | nindent 4 }}
