# Default values for camel-web-service.
# This is a YAML-formatted file.

nameOverride: ""
fullnameOverride: ""

image:
  # sample image that uses port 9000 and 8080 for Actuator
  repository: ghcr.io/ms3inc/tavros/test-api
  tag: "0.1.0-SNAPSHOT"
  pullPolicy: Always
imagePullSecrets:
- name: "tavros-artifacts-registry"

podEnvVars: []

podAnnotations: {}

service:
  annotations: {}
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/protocols: https
    kubernetes.io/ingress.class: sandbox
    cert-manager.io/cluster-issuer: tavros
    konghq.com/https-redirect-status-code: '302'
  hosts:
    - host: apps.example.com
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

readinessProbe:
  failureThreshold: 2
  initialDelaySeconds: 30
  periodSeconds: 10

livenessProbe:
  failureThreshold: 2
  initialDelaySeconds: 60
  periodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 3000

serviceAccount:
  create: false
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
