name: Unit Test (!main)

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run helm unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          helm unittest tavros/camel-web-service